config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'static_pages#index'
  
  resources :reviews do
    resources :votes, only: [:create, :destroy]
  end
  resources :movies
  resources :users do
    resources :relationships, only: [:create, :destroy]
  end
  
  get 'timeline' => 'users#timeline'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
    
    validate :title, :year, :rated, :released, :runtime, :genre, :director, :writer, :actors, :plot, :language, :country, :awards, :poster, :metascore, :imdbrating, :imdbvotes, :imdbid
    has_many :reviews
    
    scope :recent, -> {order("created_at DESC").limit(8)}
    
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower, :followed, presence: true
  validates :followed_id, uniqueness: {scope: :follower_id}
end

app/models/review.rb
class Review < ActiveRecord::Base
  validate :user, :movie, :comment
  belongs_to :user
  belongs_to :movie
  has_many :votes
  
  scope :recent, -> {order("created_at DESC").limit(5)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  
  validates :username, presence: true
  has_many :reviews
  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  has_many :followed_users, through: :followed_relationships, source: :follower
  has_many :votes
  
  def reviewed?(movie)
    reviews.exists?(movie_id: movie.id)
  end
  
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(user)
    return true if following_relationships.exists?(followed_id: user.id)
  end
  
  def voted_up_on?(review)
    votes.exists?(review_id: review.id)
  end
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :review
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protect_from_forgery with: :exception
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :username, :password, :password_confirmation, :name, :avatar) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :username, :introduction, :current_password, :password_confirmation, :name, :avatar) }
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @movies = Movie.all.includes(:reviews)
    end
    
    def show
        @movie =  Movie.find(params[:id])
        @reviewed = current_user.reviewed?(@movie)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_user
    
    def create
        current_user.follow(@user)
        
        respond_to do |format|
            format.html { redirect_to user_path(@user.id) }
            format.js {}
        end
    end
    
    def destroy
        current_user.unfollow(@user)
        
        respond_to do |format|
            format.html { redirect_to user_path(@user.id) }
            format.js {}
        end
    end
    
    private
    
    def check_user
        @user = User.find(params[:user_id])
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @movie = MovieBuilder.new(imdbid: params[:imdbid]).build!
        @review = current_user.reviews.new(review_params.merge(movie: @movie))
        
        if @review.save
            flash[:success] = "Review saved!"
            redirect_to movie_path(@movie.id)
        else
            flash[:alert] = "Woops! Something went wrong."
            redirect_to movie_path(@movie.id)
        end
    end
    
    private
    
    def review_params
        params.require(:review).permit(:comment)
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def index
        @movie = Movie.recent
        @recent_reviews = Review.recent
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
        @movies = Movie.all.includes(:reviews)
    end
    
    def timeline
        @reviews = Review.where(user_id: current_user.following_users).order("created_at DESC")
    end
    
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    
    def create
        @review = Review.find(params[:review_id])
        @review.votes.create(user_id: current_user.id)
        
        respond_to do |format|
            format.html { redirect_to movie_path }
            format.js {}
        end
    end
    
    def show
        @votes = current_user.votes.find_by(review_id: @review.id)
    end
    
    def destroy
        @review = Review.find(params[:review_id])
        @vote = Vote.find_by(user_id: params[:user_id])
        @vote.destroy
        
        respond_to do |format|
            format.html { redirect_to movie_path }
            format.js {}
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OMRv - Filmster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Lobster|Playfair+Display" rel="stylesheet">
  <link rel="icon" type="image/ico" href="/favicon.ico">
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'OMRv',  root_path, class:"navbar-brand" %>
      </div>
      
      <div class="collapse navbar-collapse" id="collapse">
        <ul class='nav navbar-nav navbar-right'>
          <% if user_signed_in? %>
            <li><%= link_to 'Timeline', timeline_path %></li>
            <li><%= link_to 'Profile', user_path(current_user.id) %></li>
            <li><%= link_to 'Edit User', edit_user_registration_path %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/movies/_likes.html.erb
<% if user_signed_in? %>
  <span class="review_like">
    <% if current_user.voted_up_on? review %>
      <%= link_to '<i class="fa fa-star fa-2x" aria-hidden="true"></i>'.html_safe, review_vote_path(review_id: review.id, user_id: current_user.id, id: current_user.votes.find_by(review_id: review.id)), method: :delete, remote: true %>
    <% else %>
      <%= link_to '<i class="fa fa-star-o fa-2x" aria-hidden="true"></i>'.html_safe, review_votes_path(review_id: review.id), method: :post, remote: true %>
    <% end %>
    <%= pluralize review.votes.size, "vote" %>
  </span>
<% else %>
  <span class="review_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize review.votes.size, "vote" %>
  </span>
<% end %>

app/views/movies/index.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4">
        <h1 class="text-center">Find Movies</h1>
        
        <div class="row">
            <form id="movie-search">
                <div class="col-xs-8">
                    <input type="text" name="s" class="form-control pull-right" placeholder="Enter Movie Name">
                </div>
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-success">Search</button>
                </div>
            </form>
        </div>
    </div>
    
    <div class="col-xs-12 col-xs-8">
        <div class="container">
            <div id="movies">
                <% @movies.each do |m| %>
                    <div class="box panel panel-default pull-left">
                        <%= link_to image_tag(m.poster == "N/A" ? "default_image.png" : m.poster), movie_path(m.id) %>
                        <div class="panel-body">
                            <p><%= m.title %></p>
                            <p><%= m.year %></p>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/movies/show.html.erb
<div class="col-xs-12 col-xs-8">
    <div class="container">
        <div id="movies">
            <div class="col-xs-4 col-md-4">
                <%= image_tag(@movie.poster == "N/A" ? "default_image.png" : @movie.poster) %>
            </div>
            
            <div class="col-xs-6 col-md-8">
                <h1><%= @movie.title %></h1>
                <h1><%= @movie.year %></h1><hr />
                <p><label>Actors: </label> <%= @movie.actors %><br />
                <label>Awards: </label> <%= @movie.awards %><br />
                <label>Country: </label> <%= @movie.country %><br />
                <label>Director: </label> <%= @movie.director %><br />
                <label>Genre: </label> <%= @movie.genre %><br />
                <label>Language: </label> <%= @movie.language %><br />
                <label>Metascore: </label> <%= @movie.metascore %><br />
                <label>Plot: </label> <%= @movie.plot %><br />
                <label>Rated: </label> <%= @movie.rated %><br />
                <label>Released: </label> <%= @movie.released %><br />
                <label>Runtime: </label> <%= @movie.runtime %><br />
                <label>Writer: </label> <%= @movie.writer %><br />
                <label>OMRv Rating: </label> <%= @movie.imdbrating %><br />
                <label>OMRv Votes: </label> <%= @movie.imdbvotes %></p><hr />
                
                <% if @reviewed%>
                    <% @movie.reviews.each do |review| %>
                        <blockquote class="review-vote">
                            <p><%= review.comment %></p>
                            <i><%= link_to review.user.username, user_path(review.user.id) %></i>
                            <span id="likes_container_<%= review.id %>" class="badge pull-right">
                              <%= render partial: 'likes', locals: {review: review} %>
                            </span>
                        </blockquote>
                    <% end %>
                <% else %>
                    <% @movie.reviews.each do |review| %>
                        <blockquote class="review-vote">
                            <p><%= review.comment %></p>
                            <i><%= link_to review.user.username, user_path(review.user.id) %></i>
                            <span id="likes_container_<%= review.id %>" class="badge pull-right">
                              <%= render partial: 'likes', locals: {review: review} %>
                            </span>
                        </blockquote>
                    <% end %>
                    <form id="rating-form" action="/reviews" method="POST">
                        <input type="hidden" name="authenticity_token" value=${window._token} />
                        <input type="hidden" name="imdbid" value=<%= @movie.imdbid %> />
                        <textarea name= "review[comment]" class="form-control" placeholder="Your movie review"/></textarea>
                        <br />
                        <input type="submit" class="btn btn-success pull-right" />
                    </form>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/relationships/create.js.erb
$('#follow-button').html("<%= escape_javascript render partial: '/users/follows', locals: {user: @user} %>");

app/views/relationships/destroy.js.erb
$('#follow-button').html("<%= escape_javascript render partial: '/users/follows', locals: {user: @user} %>");

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <% if message_type == "notice" %>
        <p class="alert alert-info alert-dismissible text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button><%= notice %>
        </p>
    <% elsif message_type == "alert" %>
        <p class="alert alert-danger alert-dismissible text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button><%= alert %>
        </p>
    <% else %>
        <div class="alert alert-<%= message_type %> alert-dismissible text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button><%= message %></div>
    <% end %>
<% end %>

app/views/static_pages/index.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4">
        <h1 class="text-center">Find Movies</h1>
        
        <div class="row">
            <form id="movie-search">
                <div class="col-xs-8">
                    <input type="text" name="s" class="form-control pull-right" placeholder="Enter Movie Name">
                </div>
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-success">Search</button>
                </div>
            </form>
        </div>
    </div>
    
    <div class="col-xs-12 col-md-3 pull-left">
        <h2 class="text-center" style="background-color: #fff; margin-bottom: 5px;" >Recent Reviews</h2>
        <% @recent_reviews.each do |r| %>
            <ul class="recent-reviews-list">
                <li>
                    <p><%= link_to r.movie.title, movie_path(r.movie.id) %></p>
                    <p><%= r.comment %><p>
                    -<%= link_to r.user.username,  user_path(r.user.id) %>
                </li>
            </ul><hr />
        <% end %>
    </div>
        
    <div class="col-xs-12 col-md-8 pull-left">
        <div id="movies">
            <% @movie.each do |m| %>
                <div class="box panel panel-default pull-left">
                    <%= link_to image_tag(m.poster == "N/A" ? "default_image.png" : m.poster, "data-id" => m.imdbid), movie_path(m.id) %>
                    <div class="panel-body">
                        <p><%= m.title %></p>
                        <p><%= m.year %></p>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    
</div>

app/views/users/_follows.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "Following", user_relationship_path(user_id: user.id, id: current_user.id), id: "unfollow-button", class: 'btn btn-default btn-success btn-unfollow', method: :delete, remote: true %>
  <% else %>
    <%= link_to "Follow", user_relationships_path(user.id), id: "follow-button", class: 'btn btn-default btn-follow', method: :post, remote: true %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= image_tag(@user.avatar_url == nil ? "fallback/no_photo.png" : @user.avatar, class: 'prof-pic-lg') %>
<h1 class="text-center"><%= @user.username %></h1>
<p class="text-center lead"><%= @user.introduction %></p>
<div id="follow-button">
    <%= render partial: 'follows', locals: {user: @user} %>
</div>
<ul class="user-stats">
    <li id="user-reviews">
        <div class="number-label"><%= "Review".pluralize(@user.reviews.count) %></div>
        <div class="number-value"><%= @user.reviews.count %></div>
    </li>
    <li id="user-following">
        <div class="number-label"><%= "Following".pluralize(@user.following_relationships.count) %></div>
        <div class="number-value"><%= @user.following_relationships.count %></div>
    </li>
    <li id="user-followers">
        <div class="number-label"><%= "Follower".pluralize(@user.followed_relationships.count) %></div>
        <div class="number-value"><%= @user.followed_relationships.count %></div>
    </li>
</ul>
<br />

<div id="movies">
    <% if @user.reviews.count < 1 %>
        <p class="text-center">This user haven't reviewed any movies yet.</p>
    <% else %>
        <% @movies.each do |m| %>
            <% if @user.reviewed?(m) %>
                <div class="box panel panel-default pull-left">
                    <%= link_to image_tag(m.poster == "N/A" ? "default_image.png" : m.poster, "data-id"=>m.imdbid), movie_path(m.id) %>
                    <div class="panel-body">
                        <p><%= m.title %></p>
                        <p><%= m.year %></p>
                    </div>
                </div>
            <% end %>
        <% end %>
    <% end %>
</div>

<script type="text/javascript">
 
$(function(){
    
    $('#movies').imagesLoaded(function(){
        $('#movies').masonry({
            itemSelector: '.panel',
            fitWidth: true
        }); 
    });
    
    let userId = <%= params[:id] %>;
    let userData = {};
    
    $.ajax({
        url: `/users/${userId}.json`,
        type: "GET"
    }).done(function(data){
        userData = data;
        console.log(userData);
    });
    
    $('#user-reviews').on('click', function(e){
        getReviews();
    });
    
    function getReviews(){
        let container = $('#movies');
        let htmlString = "";
        
        if (userData.reviews.length > 0) {
            userData.reviews.forEach(function(review){
                
                htmlString +=
                    `
                        <div class="box panel panel-default pull-left">
                            <img src=${review.movie.poster == "N/A" ? "/assets/default_image.png" : review.movie.poster} data-id="${review.movie.imdbid}" />
                            <div class="panel-body">
                                <p>${review.movie.title}</p>
                                <p>${review.movie.year}</p>
                            </div>
                        </div>
                    `;
            });
        } else {
            htmlString = `<p class="text-center">This user have not reviewed any movies yet.</p>`;
        }
        
        container.empty();
        container.append(htmlString);
        container.imagesLoaded(function(){
            container.masonry({
                itemSelector: '.panel',
                fitWidth: true
            });
        });
    }
    
    $('#user-following').on('click', function(e){
        getFollowing();
    });
    
    function getFollowing(){
        let container = $('#movies');
        let htmlString = "";
        
        if (userData.following_relationships.length > 0) {
            userData.following_relationships.forEach(function(users){
                
                htmlString +=
                    `
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <ul class="user-relationship-list">
                                <li>
                                    <img src=${users.user.avatar_url == null ? "fallback/default_image.png" : users.user.avatar_url} class="prof-pic-sm" />
                                    <a href=${users.user.id}>${users.user.username}</a>
                                    <p>${users.user.introduction == null ? "" : users.user.introduction}<p>
                                </li><hr />
                            </ul>
                        </div>
                    `;
            });
        } else {
            htmlString = `<p class="text-center">This user is not following anyone yet.</p>`;
        }
        
        container.empty();
        container.append(htmlString);
    }
    
    $('#user-followers').on('click', function(e){
        getFollowers();
    });
    
    function getFollowers(){
        let container = $('#movies');
        let htmlString = "";
        
        if (userData.followed_relationships.length > 0) {
            userData.followed_relationships.forEach(function(users){
                
                htmlString +=
                    `
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <ul class="user-relationship-list">
                                <li>
                                    <img src=${users.user.avatar_url == null ? "fallback/default_image.png" : users.user.avatar_url} class="prof-pic-sm" />
                                    <a href=${users.user.id}>${users.user.username}</a>
                                    <p>${users.user.introduction == null ? "" : users.user.introduction}<p>
                                </li><hr />
                            </ul>
                        </div>
                    `;
            });
        } else {
            htmlString = `<p class="text-center">This user is not followed by anyone yet.</p>`;
        }
        
        container.empty();
        container.append(htmlString);
    }
    
})
    
</script>

app/views/users/timeline.html.erb
<h1 class="text-center">Timeline</h1>

<div id="movies">
</div>

<script type="text/javascript">

$(function(){
    $('#movies').imagesLoaded(function(){
        $('#movies').masonry({
            itemSelector: '.panel',
            fitWidth: true
        });
    });
    
    let userData = {};
    
    $.ajax({
        url: '/timeline.json',
        type: "GET"
    })
    .done(function(data){
        //userData = data;
        displayTimeline(data);
        console.log(data);
    });
    
    function displayTimeline(dataObject)
    {
        let $container = $("#movies");
        let htmlString = "";
        
        dataObject.reviews.forEach(function(review){
            htmlString +=
                    `
                        <div class="box panel panel-default pull-left">
                            <a href="/movies/${review.movie.id}">
                                <img src=${review.movie.poster == "N/A" ? "default_image.png" : review.movie.poster} data-id="${review.movie.imdbid}" />
                            </a>
                            <div class="panel-body">
                                <p>${review.movie.title}</p>
                                <p>${review.movie.year}</p><hr />
                                <blockquote>
                                    <p>${review.comment}</p>
                                    <i><a href="/users/${review.user.id}">${review.user.username}</a></i>
                                </blockquote>
                            </div>
                        </div>
                    `;
        });
        
        $container.empty();
        $container.append(htmlString);
        $container.imagesLoaded(function(){
            $container.masonry({
                itemSelector: ".panel",
                fitWidth: true
            });
        });
    }
});
  
</script>

app/views/votes/create.js.erb
$("#likes_container_<%= @review.id %>").html("<%= escape_javascript render partial: 'movies/likes', locals: {review: @review} %>");

app/views/votes/destroy.js.erb
$("#likes_container_<%= @review.id %>").html("<%= escape_javascript render partial: 'movies/likes', locals: {review: @review} %>");